#!/bin/sh

set -e

case "$1" in
    configure)
        if ! udevadm control --reload; then
            echo "udevadm control --reload failed, ignoring" >&2
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
